Loaded the project, but didn't continue
Select project file worked, looks to be loading the right revit file, but it got stuck at 100% "Open an existing project: Regenerating". Probably need to figure out the end of the script where methods are being called.

IronPython Traceback:
Traceback (most recent call last):
 File "C:\Users\acrossonbouwers\Documents\GitHub\rjc-development\rjcCustomPythonTools\rjcTools.extension\RJC Tools.tab\RJC Tools.panel\Import From Project.pushbutton\script.py", line 547, in <module>
TypeError: 'Document' object is not iterable